[mypy]
python_version = 3.10
strict = True
warn_return_any = True
warn_unused_configs = True
disallow_untyped_defs = True
plugins = pydantic.mypy

[mypy-textstat.*]
ignore_missing_imports = True

[mypy-lexicalrichness.*]
ignore_missing_imports = True

[mypy-language_tool_python.*]
ignore_missing_imports = True

[mypy-wordfreq.*]
ignore_missing_imports = True

[mypy-easse.*]
ignore_missing_imports = True

[mypy-spacy.*]
ignore_missing_imports = True

[mypy-nltk.*]
ignore_missing_imports = True

[mypy-sentence_transformers.*]
ignore_missing_imports = True
